language: cpp
compiler:
#  - clang
  - gcc
env:
  - SPII_BUILD_TYPE=Debug
  - SPII_BUILD_TYPE=Release
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libeigen3-dev
 - sudo apt-get install -qq g++-4.9
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
before_script:
  - mkdir build
  - cd build
  - cmake -DOPENMP=OFF -DCMAKE_BUILD_TYPE=${SPII_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=/usr ..
script: 
  - make && ctest --output-on-failure && sudo make install
after_success:
  - cd ..
  - cd examples
  - ${CXX} -std=c++0x -I/usr/include/eigen3 -I/usr/include/eigen3 -I/usr/lib/eigen3 standalone_example.cpp -lspii
  - ./a.out

branches:
  only:
    - master
    - ci
